#ifndef ERROR_ENUM
#define ERROR_ENUM

// Global defines
#define MAXIMUM_MATRICES_ON_GLOBAL 100

// Matrix defines
#define MAX_DIMENSIONS 1024
#define MATRIX_MAX_NAME_SIZE 64


enum INTERFACE_CODE {
    ADD_TWO_MATRICES,
    CALCULATE_THE_DETERMINANT,
    BACK_TO_MENU
};


//Todo create all the error codes
enum ERRO_CODE{

    // matrix creation errors
    MATRIX_DIMENSION_NOT_MATCH_ITS_SIZE,
    MATRIX_DIMENSION_OUTSIDE_PERMITED_BOUNDERIES,
    MATRIX_DIMENSION_NOT_MATCHING_DATASIZE,
    MATRIX_DIMENSION_EQUAL_ZERO,
    MATRIX_DATA_EMPTY,
    MATRIX_SHAPE_OUTSIDE_PERMITED_BOUNDERIES,

    // memory allocation errors
    MEMORY_ALLOCATION_FAILED,
    FAILED_TO_FREE_MEMORY,
    GLOBAL_ARRAY_FULL,

    // user input errors
    INVALID_INPUT,

    // operation errors
    MATRIX_DIMENSION_SIZE_DONT_MATCH,
    MATRIX_SHAPE_DONT_MATCH,
    MATRIX_DATA_SIZE_DONT_MATCH,
    MATRIX_NOT_SQUARE,
    MATRIX_HAS_TOO_MANY_DIMENSIONS,
    MATRIX_NOT_SOLVABLE_BY_LU_DECOMPOSITION,

    // general signals
    COMMON_ERRO,
    NO_ERROR
};

#endif